build:
  env:
    - CGO_ENABLED=0
    - GOOS=darwin
    - GOARCH=amd64

release:
  github:
    owner: your-username
    name: your-repo

  build:
    main: .

#  checksum:
#    name_template: 'checksums.txt'
#
#  binaries:
#    - bin/*
