[project]
name = "protocol"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "DaiYuANg", email = "138393979+DaiYuANg@users.noreply.github.com" }
]
dependencies = [
    "PySide6>=6.6.2",
    "injector>=0.21.0",
    "qt-material>=2.14",
    "loguru>=0.7.2",
    "peewee>=3.17.1",
]
readme = "README.md"
requires-python = ">= 3.12"


[tool.rye]
managed = true
virtual = true
dev-dependencies = [
    "pyinstaller>=6.5.0",
]

