[project]
name = "qchat"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "DaiYuANg", email = "138393979+DaiYuANg@users.noreply.github.com" }
]
dependencies = [
    "PySide6>=6.6.2",
    "qt-material>=2.14",
    "pynput>=1.7.6",
    "openai>=1.17.0",
]
readme = "README.md"
requires-python = ">= 3.12"

[tool.rye]
managed = true
virtual = true
dev-dependencies = []
